# Generated by Django 4.2.5 on 2023-12-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_tag_product_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tag',
            new_name='tags',
        ),
    ]
